method_name: OBDECOC + RCM (w-o CorrectPenalty)
base_method_name: OBDECOC
use_rankcl: true
use_reweight: false
out_dir: output
best_hyperparams_dir: configs/results_hyperparams
seed: 0
num_workers: 4
dataset:
  dataset_name: adience
  dataset_type: image
model:
  model_params:
    feat_dims:
    - 32
    - 16
train:
  n_runs: 5
  epochs: 400
  batch_size: 128
  weight_decay: 0
  optimizer: Adam
  val_epoch: 1
  patience: 50
  best_metric_name: QWK
  val_ratio: 0.15
rankcl:
  with_correct_penalty: false
  similarity_metric: cosine
